[package]
name = "minecraft_panel_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foxhole = "0.3.0"
models = { path = "../models" }
